In [1]:
#Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
#Reading the file
df=pd.read_csv('Data_MADE_2.csv')
df_2=pd.read_csv('Data_MADE_2.csv')
df.head()

Temperature  Dissolved Oxygen    pH  Bio-Chemical Oxygen Demand (mg/L)  \
0          7.5              9.95  7.85                               0.15   
1         11.0              9.65  7.70                               0.45   
2          7.5              9.90  7.65                               0.55   
3          8.5              9.65  7.55                               0.35   
4         10.0              9.55  7.80                               0.25   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                               90.0            0.255   
1                              205.0            0.200   
2                              100.0            0.100   
3                              300.0            0.250   
4                              190.0            0.150   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                           22.5                         180.0   
1                           62.5                         410.0   
2                           26.0                         200.0   
3                           97.5                         600.0   
4                           47.5                         380.0   

   Conductivity (mho/ Cm)  
0                   134.5  
1                    77.0  
2                   101.5  
3                   148.0  
4                   106.0

In [3]:
df_2.shape

(295, 9)

In [4]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Temperature                        295 non-null    float64
 1   Dissolved Oxygen                   295 non-null    float64
 2   pH                                 295 non-null    float64
 3   Bio-Chemical Oxygen Demand (mg/L)  295 non-null    float64
 4   Faecal Streptococci (MPN/ 100 mL)  295 non-null    float64
 5   Nitrate (mg/ L)                    295 non-null    float64
 6   Faecal Coliform (MPN/ 100 mL)      295 non-null    float64
 7   Total Coliform (MPN/ 100 mL)       295 non-null    float64
 8   Conductivity (mho/ Cm)             295 non-null    float64
dtypes: float64(9)
memory usage: 20.9 KB


In [5]:
df_2.describe()

Temperature  Dissolved Oxygen          pH  \
count   295.000000        295.000000  295.000000   
mean     20.903898          7.342034    7.754627   
std       6.051566          1.910113    0.378879   
min       0.000000          0.000000    5.350000   
25%      18.000000          6.850000    7.550000   
50%      22.500000          7.750000    7.750000   
75%      25.550000          8.600000    8.000000   
max      30.500000         10.250000    8.600000   

       Bio-Chemical Oxygen Demand (mg/L)  Faecal Streptococci (MPN/ 100 mL)  \
count                         295.000000                         295.000000   
mean                            3.544136                        7463.333729   
std                             9.043299                       26272.135186   
min                             0.000000                           0.000000   
25%                             0.725000                          29.225000   
50%                             1.600000                         240.000000   
75%                             3.100000                        2650.000000   
max                           123.500000                      229000.000000   

       Nitrate (mg/ L)  Faecal Coliform (MPN/ 100 mL)  \
count       295.000000                     295.000000   
mean          0.870915                    5983.661695   
std           1.431247                   22934.986514   
min           0.000000                       0.000000   
25%           0.155000                       4.000000   
50%           0.550000                      79.500000   
75%           0.950000                    2375.000000   
max          14.050000                  251000.000000   

       Total Coliform (MPN/ 100 mL)  Conductivity (mho/ Cm)  
count                    295.000000              295.000000  
mean                   14926.667458              501.860678  
std                    52544.270371              798.311280  
min                        0.000000                0.000000  
25%                       58.450000              208.250000  
50%                      480.000000              299.500000  
75%                     5300.000000              438.250000  
max                   458000.000000             9272.000000

In [6]:
c=df.columns
c

Index(['Temperature', 'Dissolved Oxygen', 'pH',
       'Bio-Chemical Oxygen Demand (mg/L)',
       'Faecal Streptococci (MPN/ 100 mL)', 'Nitrate (mg/ L)',
       'Faecal Coliform (MPN/ 100 mL)', 'Total Coliform (MPN/ 100 mL)',
       'Conductivity (mho/ Cm)'],
      dtype='object')

In [7]:
df_2.head(10)

Temperature  Dissolved Oxygen    pH  Bio-Chemical Oxygen Demand (mg/L)  \
0          7.5              9.95  7.85                               0.15   
1         11.0              9.65  7.70                               0.45   
2          7.5              9.90  7.65                               0.55   
3          8.5              9.65  7.55                               0.35   
4         10.0              9.55  7.80                               0.25   
5         11.0              9.45  7.75                               0.85   
6          9.5              9.55  7.90                               0.50   
7         10.5              9.85  7.70                               0.25   
8         14.5              9.80  7.95                               0.25   
9         16.5              9.25  7.65                               0.25   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                               90.0            0.255   
1                              205.0            0.200   
2                              100.0            0.100   
3                              300.0            0.250   
4                              190.0            0.150   
5                              222.5            0.300   
6                              285.0            0.195   
7                              145.0            0.115   
8                              112.5            0.100   
9                              147.5            0.150   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                           22.5                         180.0   
1                           62.5                         410.0   
2                           26.0                         200.0   
3                           97.5                         600.0   
4                           47.5                         380.0   
5                           67.0                         445.0   
6                           74.5                         570.0   
7                           60.0                         290.0   
8                           26.5                         225.0   
9                           66.0                         295.0   

   Conductivity (mho/ Cm)  
0                   134.5  
1                    77.0  
2                   101.5  
3                   148.0  
4                   106.0  
5                    97.5  
6                   203.5  
7                    95.5  
8                    99.0  
9                   111.5

In [8]:
#Values of ideal drinking water
df_ideal=pd.DataFrame({'Temperature':25,
                       'Dissolved Oxygen':7.25,
                       'pH':7.5,
                       'Bio-Chemical Oxygen Demand (mg/L)':6,
                       'Faecal Streptococci (MPN/ 100 mL)':500,
                       'Nitrate (mg/ L)':4,
                       'Faecal Coliform (MPN/ 100 mL)':100,
                       'Total Coliform (MPN/ 100 mL)':5000,
                       'Conductivity (mho/ Cm)':500},index=[0])
df_ideal

Temperature  Dissolved Oxygen   pH  Bio-Chemical Oxygen Demand (mg/L)  \
0           25              7.25  7.5                                  6   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                                500                4   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                            100                          5000   

   Conductivity (mho/ Cm)  
0                     500

In [9]:
df_ideal=1/(df_ideal)
df_ideal.head()

Temperature  Dissolved Oxygen        pH  Bio-Chemical Oxygen Demand (mg/L)  \
0         0.04          0.137931  0.133333                           0.166667   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                              0.002             0.25   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                           0.01                        0.0002   

   Conductivity (mho/ Cm)  
0                   0.002

In [10]:
s=df_ideal.iloc[0].values.sum()
s

0.7421310344827586

In [11]:
k=1/s
k

1.3474709364458364

In [12]:
#Values of ideal drinking water
df_ideal=pd.DataFrame({'Temperature':k/25,
                       'Dissolved Oxygen':k/7.25,
                       'pH':k/7.5,
                       'Bio-Chemical Oxygen Demand (mg/L)':k/6,
                       'Faecal Streptococci (MPN/ 100 mL)':k/500,
                       'Nitrate (mg/ L)':k/4,
                       'Faecal Coliform (MPN/ 100 mL)':k/100,
                       'Total Coliform (MPN/ 100 mL)':k/5000,
                       'Conductivity (mho/ Cm)':k/500},index=[0])
df_ideal

Temperature  Dissolved Oxygen        pH  Bio-Chemical Oxygen Demand (mg/L)  \
0     0.053899          0.185858  0.179663                           0.224578   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                           0.002695         0.336868   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                       0.013475                      0.000269   

   Conductivity (mho/ Cm)  
0                0.002695

In [13]:
w=df_ideal.iloc[0].values.sum()
w

1.0

In [14]:
ideal_value_V0=pd.DataFrame({'Temperature':25,
                             'Dissolved Oxygen':0,
                             'pH':7,
                             'Bio-Chemical Oxygen Demand (mg/L)':0,
                             'Faecal Streptococci (MPN/ 100 mL)':0,
                             'Nitrate (mg/ L)':0,
                             'Faecal Coliform (MPN/ 100 mL)':0,
                             'Total Coliform (MPN/ 100 mL)':0,
                             'Conductivity (mho/ Cm)':0},index=[0])
ideal_value_V0

Temperature  Dissolved Oxygen  pH  Bio-Chemical Oxygen Demand (mg/L)  \
0           25                 0   7                                  0   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                                  0                0   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                              0                             0   

   Conductivity (mho/ Cm)  
0                       0

In [15]:
df_2.head()

Temperature  Dissolved Oxygen    pH  Bio-Chemical Oxygen Demand (mg/L)  \
0          7.5              9.95  7.85                               0.15   
1         11.0              9.65  7.70                               0.45   
2          7.5              9.90  7.65                               0.55   
3          8.5              9.65  7.55                               0.35   
4         10.0              9.55  7.80                               0.25   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                               90.0            0.255   
1                              205.0            0.200   
2                              100.0            0.100   
3                              300.0            0.250   
4                              190.0            0.150   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                           22.5                         180.0   
1                           62.5                         410.0   
2                           26.0                         200.0   
3                           97.5                         600.0   
4                           47.5                         380.0   

   Conductivity (mho/ Cm)  
0                   134.5  
1                    77.0  
2                   101.5  
3                   148.0  
4                   106.0

In [16]:
df_ideal.head()

Temperature  Dissolved Oxygen        pH  Bio-Chemical Oxygen Demand (mg/L)  \
0     0.053899          0.185858  0.179663                           0.224578   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                           0.002695         0.336868   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                       0.013475                      0.000269   

   Conductivity (mho/ Cm)  
0                0.002695

In [17]:
l=list()

In [18]:
l_2=[25,7.25,7.5,6,500,4,100,5000,500]
for i in range(295):
    l.append(df_2.iloc[i].values/l_2)
# VndivSn=pd.DataFrame(l)#columns=['Temperature','Dissolved Oxygen','pH','Bio-Chemical Oxygen Demand (mg/L)','Faecal Streptococci (MPN/ 100 mL)','Nitrate (mg/ L)','Faecal Coliform (MPN/ 100 mL)','Total Coliform (MPN/ 100 mL)','Conductivity (mho/ Cm)'])
# VndivSn.head()

In [19]:
l

[array([0.3       , 1.37241379, 1.04666667, 0.025     , 0.18      ,
        0.06375   , 0.225     , 0.036     , 0.269     ]),
 array([0.44      , 1.33103448, 1.02666667, 0.075     , 0.41      ,
        0.05      , 0.625     , 0.082     , 0.154     ]),
 array([0.3       , 1.36551724, 1.02      , 0.09166667, 0.2       ,
        0.025     , 0.26      , 0.04      , 0.203     ]),
 array([0.34      , 1.33103448, 1.00666667, 0.05833333, 0.6       ,
        0.0625    , 0.975     , 0.12      , 0.296     ]),
 array([0.4       , 1.31724138, 1.04      , 0.04166667, 0.38      ,
        0.0375    , 0.475     , 0.076     , 0.212     ]),
 array([0.44      , 1.30344828, 1.03333333, 0.14166667, 0.445     ,
        0.075     , 0.67      , 0.089     , 0.195     ]),
 array([0.38      , 1.31724138, 1.05333333, 0.08333333, 0.57      ,
        0.04875   , 0.745     , 0.114     , 0.407     ]),
 array([0.42      , 1.35862069, 1.02666667, 0.04166667, 0.29      ,
        0.02875   , 0.6       , 0.058     , 0.191 

In [20]:
VndivSn=pd.DataFrame(l,columns=['Temperature','Dissolved Oxygen','pH','Bio-Chemical Oxygen Demand (mg/L)','Faecal Streptococci (MPN/ 100 mL)','Nitrate (mg/ L)','Faecal Coliform (MPN/ 100 mL)','Total Coliform (MPN/ 100 mL)','Conductivity (mho/ Cm)'])
VndivSn.head()

Temperature  Dissolved Oxygen        pH  Bio-Chemical Oxygen Demand (mg/L)  \
0         0.30          1.372414  1.046667                           0.025000   
1         0.44          1.331034  1.026667                           0.075000   
2         0.30          1.365517  1.020000                           0.091667   
3         0.34          1.331034  1.006667                           0.058333   
4         0.40          1.317241  1.040000                           0.041667   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                               0.18          0.06375   
1                               0.41          0.05000   
2                               0.20          0.02500   
3                               0.60          0.06250   
4                               0.38          0.03750   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                          0.225                         0.036   
1                          0.625                         0.082   
2                          0.260                         0.040   
3                          0.975                         0.120   
4                          0.475                         0.076   

   Conductivity (mho/ Cm)  
0                   0.269  
1                   0.154  
2                   0.203  
3                   0.296  
4                   0.212

In [21]:
Qn=VndivSn*100
Qn.head()

Temperature  Dissolved Oxygen          pH  \
0         30.0        137.241379  104.666667   
1         44.0        133.103448  102.666667   
2         30.0        136.551724  102.000000   
3         34.0        133.103448  100.666667   
4         40.0        131.724138  104.000000   

   Bio-Chemical Oxygen Demand (mg/L)  Faecal Streptococci (MPN/ 100 mL)  \
0                           2.500000                               18.0   
1                           7.500000                               41.0   
2                           9.166667                               20.0   
3                           5.833333                               60.0   
4                           4.166667                               38.0   

   Nitrate (mg/ L)  Faecal Coliform (MPN/ 100 mL)  \
0            6.375                           22.5   
1            5.000                           62.5   
2            2.500                           26.0   
3            6.250                           97.5   
4            3.750                           47.5   

   Total Coliform (MPN/ 100 mL)  Conductivity (mho/ Cm)  
0                           3.6                    26.9  
1                           8.2                    15.4  
2                           4.0                    20.3  
3                          12.0                    29.6  
4                           7.6                    21.2

In [22]:
l_3=[0.000593,0.002046,0.001978,0.002473,0.00003,0.003709,0.000148,0.000003,0.98902]
l_4=list()
for i in range(295):
    l_4.append(Qn.iloc[i].values*l_3)
WnQn=pd.DataFrame(l_4,columns=['Temperature','Dissolved Oxygen','pH','Bio-Chemical Oxygen Demand (mg/L)','Faecal Streptococci (MPN/ 100 mL)','Nitrate (mg/ L)','Faecal Coliform (MPN/ 100 mL)','Total Coliform (MPN/ 100 mL)','Conductivity (mho/ Cm)'])
WnQn.head()

Temperature  Dissolved Oxygen        pH  Bio-Chemical Oxygen Demand (mg/L)  \
0     0.017790          0.280796  0.207031                           0.006182   
1     0.026092          0.272330  0.203075                           0.018547   
2     0.017790          0.279385  0.201756                           0.022669   
3     0.020162          0.272330  0.199119                           0.014426   
4     0.023720          0.269508  0.205712                           0.010304   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                            0.00054         0.023645   
1                            0.00123         0.018545   
2                            0.00060         0.009272   
3                            0.00180         0.023181   
4                            0.00114         0.013909   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                       0.003330                      0.000011   
1                       0.009250                      0.000025   
2                       0.003848                      0.000012   
3                       0.014430                      0.000036   
4                       0.007030                      0.000023   

   Conductivity (mho/ Cm)  
0               26.604638  
1               15.230908  
2               20.077106  
3               29.274992  
4               20.967224

In [23]:
l_5=[]
for i in range(295):
    l_5.append(WnQn.iloc[i].sum())
sumWnQn=l_5    
l_5

[27.143962703735635,
 15.780001421839081,
 20.612438494252874,
 29.820475405172413,
 21.498569302873562,
 19.85719021724138,
 40.80496482787356,
 19.426971401436784,
 20.127407925287358,
 22.591964995977012,
 32.58445703793103,
 23.460031548850576,
 32.85586860517242,
 46.9969626608046,
 41.431892165172414,
 49.95436810229885,
 30.325038343448274,
 44.07282563166667,
 42.351042351839084,
 43.36769578517241,
 43.448035368390805,
 49.60643100218391,
 17.856553921839083,
 42.88327648666667,
 43.433825304597704,
 41.88003134816091,
 50.42990030735632,
 51.99759477183908,
 51.07649919942529,
 55.14885740804598,
 58.983326964942535,
 51.284189774137936,
 50.97599824597701,
 50.6457621408046,
 52.264028287356325,
 266.6444467667816,
 265.51622291310343,
 261.8833697427011,
 256.4534561666667,
 242.1234216821839,
 263.75014668273565,
 261.0846822454023,
 232.77941349310345,
 135.07447880028735,
 270.42215966319543,
 55.73279407471264,
 28.955141872988506,
 149.41005273,
 147.91834600448274,
 8

In [24]:
df_ideal

Temperature  Dissolved Oxygen        pH  Bio-Chemical Oxygen Demand (mg/L)  \
0     0.053899          0.185858  0.179663                           0.224578   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                           0.002695         0.336868   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                       0.013475                      0.000269   

   Conductivity (mho/ Cm)  
0                0.002695

In [25]:
WQI=l_5
WQI

[27.143962703735635,
 15.780001421839081,
 20.612438494252874,
 29.820475405172413,
 21.498569302873562,
 19.85719021724138,
 40.80496482787356,
 19.426971401436784,
 20.127407925287358,
 22.591964995977012,
 32.58445703793103,
 23.460031548850576,
 32.85586860517242,
 46.9969626608046,
 41.431892165172414,
 49.95436810229885,
 30.325038343448274,
 44.07282563166667,
 42.351042351839084,
 43.36769578517241,
 43.448035368390805,
 49.60643100218391,
 17.856553921839083,
 42.88327648666667,
 43.433825304597704,
 41.88003134816091,
 50.42990030735632,
 51.99759477183908,
 51.07649919942529,
 55.14885740804598,
 58.983326964942535,
 51.284189774137936,
 50.97599824597701,
 50.6457621408046,
 52.264028287356325,
 266.6444467667816,
 265.51622291310343,
 261.8833697427011,
 256.4534561666667,
 242.1234216821839,
 263.75014668273565,
 261.0846822454023,
 232.77941349310345,
 135.07447880028735,
 270.42215966319543,
 55.73279407471264,
 28.955141872988506,
 149.41005273,
 147.91834600448274,
 8

In [26]:
df_2['WQI']=l_5
df_2.head()

Temperature  Dissolved Oxygen    pH  Bio-Chemical Oxygen Demand (mg/L)  \
0          7.5              9.95  7.85                               0.15   
1         11.0              9.65  7.70                               0.45   
2          7.5              9.90  7.65                               0.55   
3          8.5              9.65  7.55                               0.35   
4         10.0              9.55  7.80                               0.25   

   Faecal Streptococci (MPN/ 100 mL)  Nitrate (mg/ L)  \
0                               90.0            0.255   
1                              205.0            0.200   
2                              100.0            0.100   
3                              300.0            0.250   
4                              190.0            0.150   

   Faecal Coliform (MPN/ 100 mL)  Total Coliform (MPN/ 100 mL)  \
0                           22.5                         180.0   
1                           62.5                         410.0   
2                           26.0                         200.0   
3                           97.5                         600.0   
4                           47.5                         380.0   

   Conductivity (mho/ Cm)        WQI  
0                   134.5  27.143963  
1                    77.0  15.780001  
2                   101.5  20.612438  
3                   148.0  29.820475  
4                   106.0  21.498569

In [27]:
df_2.to_csv('Results_MADE.csv')